language: ruby
sudo: false
dist: trusty

language: ruby

install: skip
script: date > file-$TRAVIS_OS_NAME.txt

# Push binaries to GitHub Releases *only* when there is a tagged commit
jobs:
  include:
    - stage: compile macos assets
      os: osx
      deploy:
        provider: releases
        api_key: $GITHUB_OATH_TOKEN
        draft: true
        skip_cleanup: true
        file: file-$TRAVIS_OS_NAME.txt
        on:
          tags: true
    - stage: compile linux assets and publish
      deploy:
        provider: releases
        api_key: $GITHUB_OATH_TOKEN
        draft: false
        skip_cleanup: true
        file: file-$TRAVIS_OS_NAME.txt
        on:
          tags: true
