install: skip
script: date > file-$TRAVIS_OS_NAME.txt

jobs:
  include:
    - stage: compile macos assets
      os: osx
      deploy: &deploy_base
        provider: releases
        api_key: $GITHUB_OATH_TOKEN
        draft: true
        skip_cleanup: true
        file: file-$TRAVIS_OS_NAME.txt
        on:
          all_branches: true
    - stage: compile linux assets and publish
      deploy:
        <<: *deploy_base
        draft: false
