language: c++
sudo: false
dist: trusty

install: skip
script:
  - cd src/
  - g++ main.cpp -o main
  - ./main
  - cp main main-$TRAVIS_OS_NAME

# Push binaries to GitHub Releases *only* when there is a tagged commit
jobs:
  include:
    - stage: Deploy macOS binary
      os: osx
      deploy:
        provider: releases
        api_key: $GITHUB_OATH_TOKEN
        draft: true
        skip_cleanup: true
        file: main-$TRAVIS_OS_NAME
        on:
          tags: true
    - stage: Deploy Linux binary and publish
      deploy:
        provider: releases
        api_key: $GITHUB_OATH_TOKEN
        draft: false
        skip_cleanup: true
        file: main-$TRAVIS_OS_NAME
        on:
          tags: true
